/*
 * hv3qjs.c --
 *
 *     Port of hv3see.c from SEE (Simple EcmaScript Engine)
 *     to QuickJS (https://bellard.org/quickjs/).
 *
 *     This file provides the C interface glue between Tcl and QuickJS,
 *     similar to what hv3see.c did for SEE.
 *
 *     NOTE: QuickJS and SEE are very different at the API level.
 */

/*-------------------------------------------------------------------------- 
 *                         Interpreter Interface
 *
 * ::qjs::interp TCL-COMMAND
 *     Create a new QJS interpreter and return it's name (which may then be used as a Tcl command) with the JavaScript wrapper of TCL-OBJECT as the global object.
 *     Interpreter command names are always generated by this code, they can be renamed if required.
 *
 * $interp destroy
 *     Delete an interpreter and all associated resources. The command $interp is deleted by this command.
 *
 * $interp global ?PROPERTY-NAME? ?VALUE?
 *     Get and set the properties of the global object, or return the associated Tcl-command. In web-browsers this is the Window object.
 *
 * $interp eval ?-file FILENAME? JAVASCRIPT
 *     Evaluate the supplied JavaScript using JS_Eval().
 *
 * $interp function NAME ARGUMENTS BODY
 *     Define a Tcl function to be used in JavaScript.
 *
 * $interp call NAME ARGUMENTS
 *     Run a JavaScript function in Tcl
 *
 * $interp proc NAME ARGUMENTS BODY
 *     Define a JavaScript function from Tcl.
 *
 * $interp tostring TCL-OBJECT
 *     Return the string form of a JavaScript object.
 *
 * $interp dispatch TCL-OBJECT EVENT-COMMAND
 *     Issue an event on a DOM object, event-command is an even-numbered Tcl list of event property-names and values.
 *
 * $interp debug objects/alloc
 *     Return a list of Tcl commands this interpreter is holding as persistent-state objects.
 */

/*-------------------------------------------------------------------------- 
 *                      Tcl-based Javascript Objects
 *
 * As well as running JavaScript code, the Tcl application must provide implementations of DOM objects to the JavaScript interpreter. Objects are provided by one of two methods:
 *
 *     1) As an argument when the ::qjs::interp is called (mandatory).
 *     2) By returning a tcl-command like {object Tcl-COMMAND} or {transient Tcl-COMMAND} from anything in the progam that will turn Tcl into JS.
 *
 * In either case, the Tcl application provides the interpreter with a command that supports the following interface:
 *
 *     When an object's property is accessed, the command will be run with the property name as an argument, and can return a value.
 *         `$command PROPERTY`
 *     When an object's property is set, the command will be run with the property name and the value; if the property is not defined, the command must return the word "NATIVE".
 *         `$command PROPERTY ARG-VALUE`
 *     For methods, when the object is called, the command will be run with the command from the 'this' object and the specified method's arguments.
 *         `$command $thisCommand ?ARG-VALUE...?`
 *     $command Events      Return a key-paired list of custom JavaScript DOM events from the command (e.g. onclick test()).
 *     $command Finalize    Run when the JavaScript object is destroyed.
 *     $command Enumerator  Return a Tcl list of the properties defined by the command.
 *
 *    proc test_dom {args} { # Command for demonstration of the global object
 *    	variable myVar
 *    	switch -exact -- [lindex $args 0] {
 *    		testProp {
 *    			if {[llength $args] == 2} { # Set method to update the variable's value
 *    				set myVar [lindex $args 1]
 *    			} else { # Get method to retrieve the variable's value
 *    				return $myVar
 *    			}
 *    		}
 *    	}
 *    }
 *
 * Argument PROPERTY is any property name called on the JavaScript object. VALUE is a JavaScript value converted into Tcl.
 *
 * Object resource management:
 *
 *     There are no resource management issues on the global object. The script must ensure that the specified command exists for the lifetime of the interpreter.
 *     For all other objects, once the object is passed to JavaScript, JavaScript is in charge of deleting the object.
 *
 *     An object is created by returning a command in one of the following three forms from a command already registered as a JS object.
 *
 *         {object    Tcl-COMMAND}
 *         {transient Tcl-COMMAND} / {method Tcl-COMMAND} (for callable objects)
 *
 *     Both forms create the same kinds of JavaScript object, but the first initialises the object in "persistent" state the second in "transient" state.
 *     Objects in "transient" state are eligible for garbage collection once the Runtime contains no more references to it.
 *     Objects in "persistent" state are not garbage collected until the interpreter is deleted.
 */
 
#include <tcl.h>
#include <quickjs.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>

/* File hv3format.c contains the code to uniformly indent JavaScript text.
 * This is used to make stuff in the debugger more readable, it is not essential (and adds a fair overhead too).
 */
#include "hv3format.c"

typedef struct QjsTimeout QjsTimeout;
typedef struct QjsJsObject QjsJsObject;

typedef struct NodeHack NodeHack;
struct NodeHack {
	JSValue *pNodeObj;
	NodeHack *pParent;	/* Parent of this node */
	int iNode;			/* Node index */
};

typedef struct EventType EventType;

typedef struct ContextOpaque {
    Tcl_Interp *interp;
	Tcl_Obj *pLog;
    uint32_t iNextTimeout;  /* Start of a linked list of QjsTimeout structures. See included file hv3timeout.c for details. */
    QjsTimeout *pTimeout;  /* Used by the timer sub-system (hv3timeout.c). */
} ContextOpaque;

/* Structure representing an interpreter instance */
typedef struct QjsInterp {
	ContextOpaque;
    JSRuntime *rt;
    JSContext *ctx;
	Tcl_HashTable objects;  /* Hash table containing the objects created by the Tcl interpreter that are currently in "persistent" state. */
    /* Linked list of QjsJsObject structures that will be removed from the aJsObject[] table next time removeTransientRefs() is called.
     * Variable iNextJsObject is used to assign unique integer ids (QjsJsObject.iKey) to QjsJsObject instances as they are created. */
    QjsJsObject *pJsObject;
	JSValue global;
	uint32_t iKeyNext;
} QjsInterp;
static unsigned int numQjsInterp = 0;
static unsigned int numFreeInterp = 0;

/* Each JavaScript object created by the Tcl-side is represented by an instance of the following struct. */
typedef struct QjsTclObject {
	Tcl_Obj *pObj;     // Tcl script for object
    Tcl_Obj **apWord;  // Array of Tcl_Obj pointers
    unsigned int nWord;       // Number of objects in array
    unsigned int nAllocWord;  // Allocated capacity
    EventType *pTypeList;  /* Used by the events sub-system (hv3events.c) */
	NodeHack *nodehandle;  /* Non-zero if this is a "node" object */
    /* This is used by objects while they reside in the QjsInterp.objects hash table. */
	Tcl_HashEntry *pEntry;
} QjsTclObject;
static unsigned int numQjsTclObject = 0;

typedef struct {JSValue v;} JSValueEntry;  // Structure for hash table entries

/* Entries in the QjsInterp.pJsObject[] linked list are instances of the following structure. */
struct QjsJsObject {
    int iKey;
    JSValue object;
    QjsJsObject *pNext;  /* Next entry in the QjsInterp.pJsObject list */
};

static Tcl_ObjCmdProc eventDispatchCmd;
static Tcl_ObjCmdProc eventDumpCmd;
static void eventTargetInit(QjsInterp*, JSValue);
static void eventTargetGlobalInit(QjsInterp*, JSValue);
static void freeEventTargetData(JSRuntime*, QjsTclObject*);
static void listenerMark(JSRuntime *rt, JSValueConst, JS_MarkFunc*);

static JSClassID QjsTclClassId, QjsTclCallClassId;
static void getExoticObj(JSRuntime*);

enum { __JS_ATOM_NULL = JS_ATOM_NULL,
#define DEF(name, str) JS_ATOM_ ## name,
#include "quickjs-atom.h"
#undef DEF
};
/* Source file hv3timeout.c contains the implementation of the 
** following methods of the Window (global) object:
**
**     setTimeout()
**     setInterval()
**     clearTimeout()
**     clearInterval()
**
** The hv3timeout.c module uses the QjsInterp.pTimeout pointer. The
** external interface (called from this file) is:
*/ 
static void interpTimeoutInit(JSContext *, JSValue);
static void interpTimeoutCleanup(QjsInterp *);
#include "hv3timeout.c"

static int allocWordArray(QjsInterp *qjs, QjsTclObject *w, int nExtra)
{
    if ((!w->nWord) || ((w->nAllocWord - w->nWord) < nExtra))
    {
        int n, rc;
        Tcl_Obj **ap;
        rc = Tcl_ListObjGetElements(qjs->interp, w->pObj, &n, &ap);
        if (rc != TCL_OK) return rc;

        w->nWord = n;
        w->nAllocWord = n + nExtra;
        w->apWord = js_malloc(qjs->ctx, sizeof(Tcl_Obj*) * w->nAllocWord);
        memcpy(w->apWord, ap, n*sizeof(Tcl_Obj*));
    }
    return TCL_OK;
}

/* Helper function to validate a JavaScript identifier */
static int isValidJSIdentifier(const char *str) {
    if (!str || !*str && !isalpha(*str) && *str != '_' && *str != '$') return 0;
    for (const char *p = str + 1; *p; p++) {
        if (!isalnum(*p) && *p != '_' && *p != '$') return 0;
    }
    return 1;
}

/*
 *---------------------------------------------------------------------------
 *
 * stringToObj --
 *
 *     Create a Tcl object containing a copy of the JSValue str. The returned object has a ref-count of 0.
 *
 * Results:
 *
 * Side effects:
 *
 *---------------------------------------------------------------------------
 */
static inline Tcl_Obj *stringToObj(JSContext *ctx, JSValue str){
	size_t l;
	const char *s = JS_ToCStringLen(ctx, &l, str);
	Tcl_Obj *p = Tcl_NewStringObj(s, l);
	JS_FreeCString(ctx, s);
	return p;
}

/* Utility: Convert QuickJS JSValue to a Tcl_Obj* */
static Tcl_Obj *qjsValueToTcl(JSContext *ctx, JSValue val) {
    Tcl_Obj *result;
	uint32_t i;
    switch (JS_VALUE_GET_TAG(val)) {
        case JS_TAG_UNDEFINED: case JS_TAG_NULL:
            result = Tcl_NewObj();  // In Tcl, the closest equivalent to null is typically an empty string
            break;
        case JS_TAG_BOOL:
            result = Tcl_NewBooleanObj(JS_ToBool(ctx, val));
            break;
        case JS_TAG_INT:
			JS_ToInt32(ctx, &i, val);
			result = Tcl_NewIntObj(i);
            break;
		case JS_TAG_FLOAT64:
			double d;
			JS_ToFloat64(ctx, &d, val);
			result = Tcl_NewDoubleObj(d);
			break;
        case JS_TAG_STRING: case JS_TAG_STRING_ROPE:
            result = stringToObj(ctx, val);
            break;
        case JS_TAG_OBJECT: {
            if (JS_IsArray(ctx, val)) {
				JS_ToUint32(ctx, &i, JS_GetPropertyStr(ctx, val, "length"));  // Get array length
				result = Tcl_NewListObj(i, NULL);
				for (uint32_t j = 0; j < i; j++) {  // Iterate through each element
					JSValue e = JS_GetPropertyUint32(ctx, val, j);
					Tcl_ListObjAppendElement(NULL, result, qjsValueToTcl(ctx, e));
				}
			} else {  // Errors are handled here
				JSClassID id = JS_GetClassID(val);
				if (id == QjsTclClassId || id == QjsTclCallClassId) {
					result = ((QjsTclObject*)JS_GetOpaque(val, id))->pObj;
				} else {
					result = stringToObj(ctx, val);
				}
			}
            break;
        }
        default:
	        result = Tcl_ObjPrintf("[TCL-JS UNKNOWN %d]", JS_VALUE_GET_TAG(val));
    }
    JS_FreeValue(ctx, val);
    return result;
}

static inline Tcl_Obj *
argValueToTcl(QjsInterp *qjs, JSValueConst val, int *pN) {
	if (JS_IsBool(val) || JS_IsString(val)) return stringToObj(qjs->ctx, val);
	if (JS_IsObject(val)) {
		JSClassID id;
        Tcl_Obj *aTclValues[2];
		aTclValues[0] = Tcl_NewStringObj("object", 6);
        QjsTclObject *pO = JS_GetAnyOpaque(val, &id);
		if (pO && id == QjsTclClassId) {
			aTclValues[1] = pO->pObj;
		} else if (pO && id == QjsTclCallClassId) {
			aTclValues[0] = Tcl_NewStringObj("method", 6);
			aTclValues[1] = pO->pObj;
		} else {
			/* Create the new QjsJsObject structure. */
			QjsJsObject *pJsObject = js_malloc(qjs->ctx, sizeof(QjsJsObject));
			pJsObject->iKey = qjs->iKeyNext++;
			pJsObject->object = val;

			pJsObject->pNext = qjs->pJsObject;
			qjs->pJsObject = pJsObject;

			aTclValues[1] = Tcl_NewIntObj(pJsObject->iKey);
			(*pN)++;
		}
        return Tcl_NewListObj(2, aTclValues);
	} 
	return qjsValueToTcl(qjs->ctx, JS_DupValue(qjs->ctx, val));
}

static void removeTransientRefs(QjsInterp *qjs, int n)
{
    while (n-- && qjs->pJsObject) {
		QjsJsObject *pJsObject = qjs->pJsObject;
        qjs->pJsObject = qjs->pJsObject->pNext;
		js_free(qjs->ctx, pJsObject);
    }
}

static int evalObjv(Tcl_Interp *interp, int nWord, Tcl_Obj **apWord){
#if 0
	printf("%d. ", nWord);
    for (int i=0; i<nWord;) printf("%d: %s. ", i++, Tcl_GetString(apWord[i]));
    printf("\n");
#endif
    return Tcl_EvalObjv(interp, nWord, apWord, TCL_EVAL_GLOBAL);
}

/*
 *---------------------------------------------------------------------------
 *
 * callQjsTclMethod --
 *
 *     This is a helper function used to call the following methods of
 *     the supplied QjsTclObject (argument p):
 *
 *         Get Put CanPut HasProperty Delete DefaultValue Enumerator
 *
 *     The other methods (Call and Construct) are invoked via
 *     tclCallOrConstruct().
 *
 * Results: 
 *     See above.
 *
 * Side effects:
 *     None.
 *
 *---------------------------------------------------------------------------
 */
static int callQjsTclMethod(
    Tcl_Interp *interp,         /* Tcl Interpreter context */
    Tcl_Obj *pLog,              /* Log command */
    JSValueConst obj,           /* Object to call method of */
    Tcl_Obj *pProp,             /* First argument (or null) */
    Tcl_Obj *pVal)              /* Second argument (or null) */
{
    int rc, nArg = 1;
	QjsTclObject *p = JS_GetOpaque(obj, JS_GetClassID(obj));

    assert(p->nAllocWord - p->nWord >= 3);

    Tcl_IncrRefCount(pProp);
	p->apWord[p->nWord] = pProp;

    if (pVal) {
        p->apWord[p->nWord+nArg] = pVal;
        nArg++;
    }

    rc = evalObjv(interp, p->nWord+nArg, p->apWord);
	
    if (pLog && rc==TCL_OK) {
        Tcl_Obj *pEval = Tcl_DuplicateObj(pLog);
        Tcl_Obj *pRes = Tcl_GetObjResult(interp);
        Tcl_IncrRefCount(pRes);

        Tcl_ListObjAppendElement(0, pEval, Tcl_NewStringObj("ECMASCRIPT", 10));
        Tcl_ListObjAppendElement(0, pEval, p->pObj);
        if (pProp) Tcl_ListObjAppendElement(0, pEval, pProp);
        if (pVal) Tcl_ListObjAppendElement(0, pEval, pVal);
        Tcl_ListObjAppendElement(0, pEval, pRes);
        Tcl_EvalObjEx(interp, pEval, TCL_EVAL_DIRECT|TCL_EVAL_GLOBAL);

        Tcl_SetObjResult(interp, pRes);
        Tcl_DecrRefCount(pRes);
    }
	
    return rc;
}

/*
 *---------------------------------------------------------------------------
 *
 * newQjsTclObject --
 *
 *     Allocate and return a pointer to a new QjsTclObject structure 
 *     based on the Tcl command passed as the second argument.
 *
 * Results:
 *     Pointer to new QjsTclObject structure.
 *
 * Side effects:
 *     None.
 *
 *---------------------------------------------------------------------------
 */
static JSValue newQjsTclObject(QjsInterp *qjs, int8_t isCall, Tcl_Obj *pTclCmd, QjsTclObject **p)
{
    QjsTclObject *qjsTclObj;
	const char **a;
	int n;

    JSValue obj = JS_NewObjectClass(qjs->ctx, isCall ? QjsTclCallClassId : QjsTclClassId);
//	printf("%p %s #%d\n", JS_VALUE_GET_PTR(obj), Tcl_GetString(pTclCmd), numQjsTclObject);
    if (JS_IsException(obj)) return obj;
	
    qjsTclObj = js_mallocz(qjs->ctx, sizeof(*qjsTclObj));
    if (!qjsTclObj) goto error;
	qjsTclObj->pObj = pTclCmd;
    JS_SetOpaque(obj, qjsTclObj);
	
	Tcl_IncrRefCount(qjsTclObj->pObj);
    if (allocWordArray(qjs, qjsTclObj, 4) != TCL_OK) {
		Tcl_DecrRefCount(qjsTclObj->pObj);
        goto error;
	}
    numQjsTclObject++;
	if (p != NULL) *p = qjsTclObj;
    return obj;
	error:
		js_free(qjs->ctx, qjsTclObj);
		JS_FreeValue(qjs->ctx, obj);
		return JS_EXCEPTION;
}

static void finalizeObject(JSRuntime *rt, JSValue val)
{
    QjsTclObject *qjsTclObj = JS_GetOpaque(val, JS_GetClassID(val));
    if (qjsTclObj) {
        /* Execute the Tcl Finalize hook. Do nothing with the result thereof. */
        Tcl_Interp *interp = JS_GetRuntimeOpaque(rt);
        if (callQjsTclMethod(interp, NULL, val, Tcl_NewStringObj("Finalize", 8), NULL) != TCL_OK) {
            Tcl_AppendResult(interp, "WARNING Qjstcl: Finalize script failed for ");
			Tcl_AppendObjToObj(Tcl_GetObjResult(interp), qjsTclObj->pObj);
        }
        for (int i = 0; i < qjsTclObj->nWord; i++) {  // Decrement reference count for each Tcl object
            Tcl_DecrRefCount(qjsTclObj->apWord[i]);
        }
        // Free the array and qjsTclObj
        js_free_rt(rt, qjsTclObj->apWord);
		assert(qjsTclObj->pObj->refCount >= 1);
		if (qjsTclObj->pEntry) {
			JSValueEntry *pV = (JSValueEntry*)Tcl_GetHashValue(qjsTclObj->pEntry);
			Tcl_DeleteHashEntry(qjsTclObj->pEntry);
			ckfree(pV);
		}
		freeEventTargetData(rt, qjsTclObj);
        js_free_rt(rt, qjsTclObj);
    }
	numQjsTclObject--;
//	printf("-%p\n", JS_VALUE_GET_PTR(val));
}

static JSValue createTransient(QjsInterp *qjs, Tcl_Obj *pTclCmd)
{
	JSValue func_obj = newQjsTclObject(qjs, 1, pTclCmd, 0);
	JS_SetConstructorBit(qjs->ctx, func_obj, 1);
    return func_obj;
}

/*
 *---------------------------------------------------------------------------
 *
 * findOrCreateObject --
 *
 * Results:
 *     Returns a JSValue representing an object, duplicated for the caller.
 *
 * Side effects:
 *     May create a new JSValueEntry structure and add it to the qjs->objects hash table.
 *     Initializes the event subsystem for new objects.
 *
 *---------------------------------------------------------------------------
 */
static JSValue findOrCreateObject(QjsInterp *qjs, Tcl_Obj *pTclCmd)
{
    Tcl_Interp *interp = qjs->interp;
    const char *zCmd = Tcl_GetString(pTclCmd);
    JSValueEntry *pObject;
    Tcl_HashEntry *pEntry;
	int isNew, iKey;
	
    /* See if this is a JavaScript object reference. It is assumed to be a JavaScript reference if the first character is a digit. */
    if (isdigit(zCmd[0])){
        if (TCL_OK != Tcl_GetIntFromObj(interp, pTclCmd, &iKey)) return JS_EXCEPTION;
	    QjsJsObject *pJsObject;
		for (
			pJsObject = qjs->pJsObject;
			pJsObject && pJsObject->iKey != iKey;
			pJsObject = pJsObject->pNext
		);
		if (!pJsObject) return JS_EXCEPTION;
		return JS_DupValue(qjs->ctx, pJsObject->object);
    }

    /* Search for an existing Tcl object */
    pEntry = Tcl_CreateHashEntry(&qjs->objects, zCmd, &isNew);

    if (isNew) {
        /* No existing entry, create a new one */
		QjsTclObject *p;
        /* Create new JSValueEntry */
        pObject = ckalloc(sizeof(*pObject));
        /* Create new object and store it */
        pObject->v = newQjsTclObject(qjs, 0, pTclCmd, &p);
        /* Insert the new object into the hash table */
        Tcl_SetHashValue(pEntry, pObject);
		p->pEntry = pEntry;
        /* Initialise the objects events subsystem. */
        eventTargetInit(qjs, pObject->v);

		Tcl_Obj *pEval = Tcl_NewStringObj("namespace tail ", 15);
		Tcl_AppendObjToObj(pEval, p->apWord[0]);
		if (Tcl_EvalObjEx(interp, pEval, TCL_EVAL_DIRECT|TCL_EVAL_GLOBAL) == TCL_OK)
			JS_DefinePropertyValue(qjs->ctx, pObject->v, JS_ATOM_Symbol_toStringTag, JS_NewString(
				qjs->ctx, Tcl_GetStringResult(interp)), 0);
    }
    /* Existing entry found */
    pObject = (JSValueEntry *)Tcl_GetHashValue(pEntry);

    /* Return a duplicated JSValue for the caller */
    return JS_DupValue(qjs->ctx, pObject->v);
}

static JSValue createNode(QjsInterp *qjs, Tcl_Obj *pTclCmd)
{
    JSValue obj = findOrCreateObject(qjs, pTclCmd);
	assert(JS_VALUE_HAS_REF_COUNT(obj));
	QjsTclObject *p = JS_GetOpaque(obj, QjsTclClassId);
    if (p->nodehandle == 0) {
        Tcl_Command t;
        Tcl_CmdInfo info;
        t = Tcl_GetCommandFromObj(qjs->interp, p->apWord[2]);
        assert(t);
        Tcl_GetCommandInfoFromToken(t, &info);
        p->nodehandle = info.objClientData;
        ((NodeHack *)p->nodehandle)->pNodeObj = JS_VALUE_GET_PTR(obj);
    }
    return obj;
}

static JSValue createBridge(QjsInterp *qjs, Tcl_Obj *pTclCmd)
{
    Tcl_Command t;
    Tcl_CmdInfo info;
    QjsInterp *foreignQjs;

    t = Tcl_GetCommandFromObj(qjs->interp, pTclCmd);
    if(!t) return JS_NULL;
    Tcl_GetCommandInfoFromToken(t, &info);
    foreignQjs = info.objClientData;
	JSValue global = foreignQjs->global;
    assert(JS_GetClassID(global) == QjsTclClassId);
    return JS_DupValue(qjs->ctx, global);
}

/* Utility: Convert Tcl_Obj* to QuickJS JSValue */
static JSValue objToValue(JSContext *ctx, Tcl_Obj *pObj) {
    // This is a stub: may want to parse Tcl lists to JS objects, etc.
	Tcl_WideInt w;
    double d;
    int n;
    if (Tcl_GetWideIntFromObj(NULL, pObj, &w) == TCL_OK) {
        return JS_NewInt64(ctx, w);
    } if (Tcl_GetDoubleFromObj(NULL, pObj, &d) == TCL_OK) {
        return JS_NewFloat64(ctx, d);
    } if (Tcl_GetIntFromObj(NULL, pObj, &n) == TCL_OK) {
        return JS_NewInt32(ctx, n);
    } if (Tcl_GetBooleanFromObj(NULL, pObj, &n) == TCL_OK) {
        return JS_NewBool(ctx, n);
    } else {  // Fallback: treat as string
		if (pObj->typePtr == Tcl_GetObjType("list")) {
			Tcl_Obj **ap;
			QjsInterp *qjs = (QjsInterp*)JS_GetContextOpaque(ctx);
			Tcl_ListObjGetElements(qjs->interp, pObj, &n, &ap);
			if (n == 0) return JS_UNDEFINED;
			if (n == 1) return objToValue(ctx, ap[0]);
			if (n == 2) {
				static const char *const aType[] = {"object", "node", "method", "bridge", "transient", NULL};
				Tcl_GetIndexFromObj(qjs->interp, ap[0], aType, "type", TCL_EXACT, &n);
				switch (n) {
					case 0: return findOrCreateObject(qjs, ap[1]); // Object
					case 1: return createNode(qjs, ap[1]); 	      // Node
					case 2: return createTransient(qjs, ap[1]);  // Method
					case 3: return createBridge(qjs, ap[1]);    // Another context's global object
					case 4: return newQjsTclObject(qjs, 0, ap[1], NULL);
				}
			}
		}
		const char *s = Tcl_GetStringFromObj(pObj, &n);
		if (!n || n == 9 && !strncmp(s, "undefined", 9)) return JS_UNDEFINED;
		if (n == 4 && !strncmp(s, "null", 4)) return JS_NULL;
        return JS_NewStringLen(ctx, s, n);
    }
}

JSValue throwTclError(JSContext *ctx, Tcl_Interp* interp) {
    JSValue err = JS_NewError(ctx);
    JSValue str = JS_NewString(ctx, Tcl_GetStringResult(interp));
    JS_SetPropertyStr(ctx, err, "message", str);
    return JS_Throw(ctx, err);
}

static JSValue createNative(QjsInterp *qjs, Tcl_Obj *pTclList)
{
    unsigned int n, i, rc;
    Tcl_Obj **ap;

    rc = Tcl_ListObjGetElements(qjs->interp, pTclList, &n, &ap);
    if (rc != TCL_OK) return throwTclError(qjs->ctx, qjs->interp);

    JSValue ret = JS_NewObject(qjs->ctx);
    for (i = 0; i < n-1; i += 2){
		JS_SetPropertyStr(qjs->ctx, ret, Tcl_GetString(ap[i]), objToValue(qjs->ctx, ap[i+1]));
    }
    return ret;
}

/*
 *---------------------------------------------------------------------------
 *
 * handleJavascriptError --
 *
 *     This function is designed to be called when a JavaScript error occurs.
 *
 * Results:
 *     Always returns TCL_ERROR.
 *
 * Side effects:
 *     Sets the result of Tcl interpreter qjs->interp.
 *
 *---------------------------------------------------------------------------
 */
static int handleJavascriptError(QjsInterp *qjs, JSValue val) {
   /* The Tcl error message is a well formed Tcl list. The elements
    * of which are as follows:
    *
    *   * The literal string "JS_ERROR"
    *   * The string form of the JavaScript object thrown.
    *   * The value of $errorInfo (if this is a Tcl error, otherwise 
    *     an empty string).
    *   * Followed by an even number of elements - alternating filenames
    *     and line numbers that make up the stack trace (first pair
    *     is at the bottom of the stack - where the exception was thrown
    *     from).
    */
    Tcl_Obj *pError = Tcl_NewObj();
    Tcl_ListObjAppendElement(0, pError, Tcl_NewStringObj("JS_ERROR", 8));
    /* If there is a Tcl error, append it. Otherwise append an empty string. */
    if (JS_IsException(val)) {
        JSValue exc = JS_GetException(qjs->ctx);
		Tcl_ListObjAppendElement(0, pError, stringToObj(qjs->ctx, exc));
		JS_FreeValue(qjs->ctx, exc);
    } else {
        Tcl_ListObjAppendElement(0, pError, Tcl_NewObj());
    }
    Tcl_SetObjResult(qjs->interp, pError);
    return TCL_ERROR;
}

/*
 *---------------------------------------------------------------------------
 *
 * delInterpCmd --
 *
 *     This function is called when a QjsInterp is deleted.
 *     Tcl command: $interp destroy 
 *
 * Results:
 *     None.
 *
 * Side effects:
 *
 *---------------------------------------------------------------------------
 */
static void delInterpCmd(ClientData cd) {
    QjsInterp *qjs = (QjsInterp*)cd;
    if (qjs) {
		if (qjs->pLog) {
			Tcl_DecrRefCount(qjs->pLog);
			qjs->pLog = NULL;
		}
		
		JS_FreeValue(qjs->ctx, qjs->global);

		Tcl_HashSearch search;
		Tcl_HashEntry* pEntry = Tcl_FirstHashEntry(&qjs->objects, &search);
		while (pEntry) {
			JSValueEntry *pO = (JSValueEntry*)Tcl_GetHashValue(pEntry);
			pEntry = Tcl_NextHashEntry(&search);
            // Set pEntry to NULL in the associated QjsTclObject to prevent finalizeObject from deleting it
            ((QjsTclObject*)JS_GetOpaque(pO->v, QjsTclClassId))->pEntry = NULL;
            JS_FreeValue(qjs->ctx, pO->v); // Decrement refcount, may trigger finalizeObject
            ckfree(pO); // Free the JSValueEntry
		}
		Tcl_DeleteHashTable(&qjs->objects);

		interpTimeoutCleanup(qjs);
		
        JS_FreeContext(qjs->ctx);
		JSRuntime *rt = qjs->rt;
        js_free_rt(rt, qjs);
		
        if (numQjsInterp-numFreeInterp < 2) JS_FreeRuntime(rt);
    } // The command is deleted by Tcl automatically
	numFreeInterp++;
}

typedef struct {
  const char *zName;
  uint8_t isBoolean;
  Tcl_Obj *pVal;
} TclCmdArg;

static int
processArgs(Tcl_Interp *interp, TclCmdArg *aOpt, int objc, Tcl_Obj *const objv[])
{
    for (int i = 0; i < objc; i++){
        Tcl_Obj *p = objv[i];
        size_t s = sizeof(TclCmdArg);
        int idx;
        if (Tcl_GetIndexFromObjStruct(interp, p, aOpt, s, "option", 0, &idx)) {
            return TCL_ERROR;
        }
        if (0 == aOpt[idx].isBoolean) {
            i++;
            if (i >= objc) {
                Tcl_AppendResult(interp, "option ", aOpt[idx].zName, " requires an argument", 0);
                return TCL_ERROR;
            }
        }
        aOpt[idx].pVal = objv[i];
    }
    return TCL_OK;
}

/*
 *---------------------------------------------------------------------------
 *
 * interpEval --
 *
 *     This function does the work of the [$qjs_interp eval JAVASCRIPT]
 *     Tcl command. Syntax:
 *
 *         $interp eval ?OPTIONS? JAVASCRIPT
 *
 *     where OPTIONS are:
 *
 *         -file  FILENAME
 *         -scope JAVASCRIPT-OBJECT
 *
 * Results:
 *     Tcl result - TCL_OK or TCL_ERROR.
 *
 * Side effects:
 *     Executes the block of JavaScript passed as parameter pCode in
 *     the global context.
 *
 *---------------------------------------------------------------------------
 */
static int interpEval(QjsInterp *qjs, int objc, Tcl_Obj *const objv[])
{
	Tcl_Interp *interp = qjs->interp;
	int rc = TCL_OK;
    TclCmdArg aOptions[] = {
        {"-file",     0, 0},
        {"-noresult", 1, 0},
        {NULL, 0, 0}
    };
	const char *file; /* Value passed to -file option */
    char noR;         /* True if -noresult */
	int l;            /* Length of script */

    if (processArgs(interp, aOptions, objc-3, &objv[2])) return TCL_ERROR;

    const char *code = Tcl_GetStringFromObj(objv[objc-1], &l); /* Javascript to evaluate */
    noR = aOptions[1].pVal != 0;

	file = aOptions[0].pVal ? Tcl_GetString(aOptions[0].pVal) : "<eval>";
    JSValue result = JS_Eval(qjs->ctx, code, l, file, JS_EVAL_TYPE_GLOBAL);

    if (JS_IsException(result)) {
        rc = handleJavascriptError(qjs, result);
	} else if (!noR) {
        Tcl_SetObjResult(interp, qjsValueToTcl(qjs->ctx, JS_DupValue(qjs->ctx, result)));
    }
	JS_FreeValue(qjs->ctx, result);
    return rc;
}

static JSValue // The following 4 functions are based on ones from dbohdan/tcl-duktape
tclLambda(JSContext *ctx, JSValueConst this, int argc, JSValueConst *argv, int m, JSValue *o)
{
	int i, rc;
	Tcl_Interp *interp = ((ContextOpaque*)JS_GetContextOpaque(ctx))->interp;
	if (!interp) return JS_ThrowTypeError(ctx, "Tcl interpreter not available");

	Tcl_Obj *pCmd = Tcl_NewStringObj("apply", 5);
    rc = Tcl_ListObjAppendElement(interp, pCmd, stringToObj(ctx, o[0]));
	if(rc!=TCL_OK) JS_ThrowTypeError(ctx, "could not append lambda");

	for (i = 0; i < argc; i++) {
        rc = Tcl_ListObjAppendElement(interp, pCmd, qjsValueToTcl(ctx, JS_DupValue(ctx, argv[i])));
		if(rc!=TCL_OK) JS_ThrowTypeError(ctx, "could not append arguments");
    }
	rc = Tcl_EvalObjEx(interp, pCmd, 0);
	if (rc != TCL_OK) return throwTclError(ctx, interp);
	return objToValue(ctx, Tcl_GetObjResult(interp));
}

static int interpFunction(QjsInterp *qjs, int objc, Tcl_Obj *const objv[])
{	
	const char *name = Tcl_GetString(objv[2]);
	if (!isValidJSIdentifier(name)) { /* Validate function name */
        Tcl_SetObjResult(qjs->interp, Tcl_ObjPrintf("Invalid function name: %s", name));
        return TCL_ERROR;
    }  // Add arguments and body
	JSValue o[1];
	o[0] = JS_NewString(qjs->ctx, Tcl_GetString(Tcl_NewListObj(2, &objv[3])));
	JSValue glb = JS_GetGlobalObject(qjs->ctx);
    JS_SetPropertyStr(qjs->ctx, glb, name, JS_NewCFunctionData(qjs->ctx, tclLambda, 1, 0, 1, o));
	JS_FreeValue(qjs->ctx, o[0]);
	JS_FreeValue(qjs->ctx, glb);
	return TCL_OK;
}

static int interpCall(QjsInterp *qjs, int objc, Tcl_Obj *const objv[])
{
	int i, n;     // Number of arguments
	Tcl_Obj **p;  // Individual arguments as Tcl objects
	
	if (Tcl_ListObjGetElements(qjs->interp, objv[3], &n, &p) != TCL_OK) { // Get arguments
		return TCL_ERROR;
	}
	JSValue args[n];
	for (i=0; i < n; i++) args[i] = objToValue(qjs->ctx, p[i]);
	
	JSValue glb = JS_GetGlobalObject(qjs->ctx);
	JSValue function = JS_GetPropertyStr(qjs->ctx, glb, Tcl_GetString(objv[2]));
	JS_FreeValue(qjs->ctx, glb);

	JSValue result = JS_Call(qjs->ctx, function, function, n, args);
	for (i=0; i < n; i++) JS_FreeValue(qjs->ctx, args[i]);
	JS_FreeValue(qjs->ctx, function);
	Tcl_SetObjResult(qjs->interp, qjsValueToTcl(qjs->ctx, result));
	JS_FreeValue(qjs->ctx, result);

	return TCL_OK;
}

static int interpProc(QjsInterp *qjs, int objc, Tcl_Obj *const objv[])
{
	int l, i, argc;
	Tcl_Obj **args, *pCode;
    const char *code, *funcName = Tcl_GetString(objv[2]);

    if (!isValidJSIdentifier(funcName)) { /* Validate function name */
        Tcl_SetResult(qjs->interp, "Invalid function name", TCL_STATIC);
        return TCL_ERROR;
    }
	/* Process comma-separated arguments */
    if (Tcl_ListObjGetElements(qjs->interp, objv[3], &argc, &args)!=TCL_OK) {
        return TCL_ERROR;
    }
	pCode = Tcl_ObjPrintf("function %s (", funcName);
    for (i = 0; i < argc; i++) {  /* Validate each argument as a JavaScript identifier */
        if (!isValidJSIdentifier(Tcl_GetString(args[i]))) {
            Tcl_SetResult(qjs->interp, "Invalid argument name", TCL_STATIC);
            return TCL_ERROR;
        }
		if (i > 0) Tcl_AppendToObj(pCode, ", ", 2);  /* Join arguments with commas */
        Tcl_AppendObjToObj(pCode, args[i]);
    }
	Tcl_AppendToObj(pCode, ")", 1);
	Tcl_ListObjAppendElement(qjs->interp, pCode, objv[4]);
	
	code = Tcl_GetStringFromObj(pCode, &l); /* Javascript to evaluate */
	JSValue result = JS_Eval(qjs->ctx, code, l, "<proc>", JS_EVAL_TYPE_GLOBAL);

	if (JS_IsException(result)) return handleJavascriptError(qjs, result);
	JS_FreeValue(qjs->ctx, result);
	return TCL_OK;
}

static int interpGlobalSet(QjsInterp *qjs, Tcl_Obj *pProp, Tcl_Obj *pVal)
{
	if (pProp == NULL) {
		QjsTclObject *w = JS_GetOpaque(qjs->global, QjsTclClassId);
		Tcl_SetObjResult(qjs->interp, w->pObj);
	} else if (pVal == NULL) {
		JSValue prop = JS_GetPropertyStr(qjs->ctx, qjs->global, Tcl_GetString(pProp));
		Tcl_SetObjResult(qjs->interp, qjsValueToTcl(qjs->ctx, prop));
	} else {
	    JS_SetPropertyStr(qjs->ctx, qjs->global, Tcl_GetString(pProp), objToValue(qjs->ctx, pVal));
	}
    return TCL_OK;
}

static inline Tcl_Obj *debugAlloc(JSRuntime *rt) {
    Tcl_Obj *pRet = Tcl_NewObj();
	JSMemoryUsage s;
    JS_ComputeMemoryUsage(rt, &s);

	const char *azNames[15] = {
		"QjsTclObject", "memory allocated", "memory used", "atoms", "strings",
		"objects", " properties", " shapes", "bytecode functions", " bytecode",
		" pc2line", "C functions", "arrays", " elements", "binary objects",
	};
	int counts[15] = {
		numQjsTclObject, s.malloc_count, s.memory_used_count, s.atom_count, s.str_count,
		s.obj_count, s.prop_count, s.shape_count, s.js_func_count, s.js_func_count,  /* bytecode uses func count */
		s.js_func_pc2line_count, s.c_func_count, s.array_count, s.fast_array_elements, s.binary_object_count,
	};
	int sizes[15] = {
		0, s.malloc_size, s.memory_used_size, s.atom_size, s.str_size,
		s.obj_size, s.prop_size, s.shape_size, s.js_func_size, s.js_func_code_size,
		s.js_func_pc2line_size, 0, 0, s.fast_array_elements*sizeof(JSValue), s.binary_object_size,
	};
	for (int i = 0; i < 15; i++) {
		Tcl_Obj *pRow = Tcl_NewObj();
		Tcl_ListObjAppendElement(NULL, pRet, Tcl_NewStringObj(azNames[i], -1));
		Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewStringObj("COUNT", 5));
		Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewIntObj(counts[i]));
		if (sizes[i] > 0) {
			Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewStringObj("SIZE", 4));
			Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewIntObj(sizes[i]));
			Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewStringObj("PER", 3));
			Tcl_ListObjAppendElement(NULL, pRow, Tcl_NewDoubleObj((double)sizes[i]/counts[i]));
		}
		Tcl_ListObjAppendElement(NULL, pRet, pRow);
    }
	return pRet;
}
/*
 *---------------------------------------------------------------------------
 *
 * interpDebug --
 *
 *    Implementation of the [$interp debug] command. This command is
 *    not required for normal operation, but provides some sub-commands
 *    useful while debugging the system.
 *    
 *       $interp debug objects
 *       $interp debug alloc
 *
 *    (Probably there are more sub-commands, peers of "objects", to come)
 *
 * Results:
 *
 * Side effects:
 *
 *---------------------------------------------------------------------------
 */
static int interpDebug(QjsInterp *qjs, int objc, Tcl_Obj *const objv[]) {
    TclCmdArg aOptions[] = {{"objects", 1, 0}, {"alloc", 1, 0}, {0, 0, 0}};
    if (processArgs(qjs->interp, aOptions, 1, &objv[2])) return TCL_ERROR;
    Tcl_Obj *pRet = Tcl_NewObj();
    if (aOptions[1].pVal) { // alloc subcommand
        pRet = debugAlloc(qjs->rt);
    } else if (aOptions[0].pVal) { // objects subcommand
		Tcl_HashSearch search;
		Tcl_HashEntry* pEntry;
		for (pEntry=Tcl_FirstHashEntry(&qjs->objects, &search); pEntry; pEntry=Tcl_NextHashEntry(&search)) {
			JSValueEntry *pObject = (JSValueEntry *)Tcl_GetHashValue(pEntry);
			Tcl_Obj *p = ((QjsTclObject*)JS_GetOpaque(pObject->v, QjsTclClassId))->pObj;
            Tcl_ListObjAppendElement(NULL, pRet, p);
		}
    }
    Tcl_SetObjResult(qjs->interp, pRet);
    return TCL_OK;
}

static int interpCmd(
    ClientData clientData,             /* The QjsInterp data structure */
    Tcl_Interp *interp,                /* Current interpreter. */
    int objc,                          /* Number of arguments. */
    Tcl_Obj *CONST objv[]              /* Argument strings. */
) {
    int rc = TCL_OK;
    QjsInterp *qjs = (QjsInterp *)clientData;
    int choice, nMin, nMax;

    enum INTERP_enum {
        INTERP_DESTROY,               /* Destroy the interpreter */
        INTERP_EVAL,                  /* Evaluate some JavaScript */
        INTERP_TOSTRING,              /* Convert js value to a string */
        INTERP_FUNC,
        INTERP_PROC,
        INTERP_CALL,
        INTERP_NODE,  // Used in hv3_dom.tcl line 300+
        INTERP_GLOBAL,
        INTERP_DISPATCH,              /* Dispatch a DOM event */
		/* Debugging API - not essential for normal operation. */
        INTERP_DEBUG,
        INTERP_LOG,
        INTERP_EVENTS,
    };
    static const struct InterpSubCommand {
        const char *zCommand;
        enum INTERP_enum eSymbol;
        uint8_t nMinArgs, nMaxArgs;
        char *zArgs;
    } aSubCommand[] = {
        {"destroy",  INTERP_DESTROY,  0, 0, ""},
        {"eval",     INTERP_EVAL,     0, 5, "?-file FILENAME? ?-noresult BOOL? JAVASCRIPT"},
        {"tostring", INTERP_TOSTRING, 1, 1, "JAVASCRIPT-VALUE"},
        {"function", INTERP_FUNC,     3, 3, "NAME ARGUMENTS BODY"},
        {"proc",     INTERP_PROC,     3, 3, "NAME ARGUMENTS BODY"},
        {"call",     INTERP_CALL,     2, 2, "NAME ARGUMENTS"},
        {"node",     INTERP_NODE,     1, 1, "TCL-COMMAND"},
        {"global",   INTERP_GLOBAL,   0, 2, "?PROPERTY? ?JAVASCRIPT-VALUE?"},
        {"dispatch", INTERP_DISPATCH, 2, 2, "TARGET-COMMAND EVENT-COMMAND"},
		{"debug",    INTERP_DEBUG,    1, 1, "SUB-COMMAND"},
		{"log",      INTERP_LOG,      1, 1, "TCL-COMMAND"},
		{"events",   INTERP_EVENTS,   1, 1, "TCL-COMMAND"},
        {NULL, 0, 0, 0}
    };
    if (objc < 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "SUBCOMMAND ...");
        return TCL_ERROR;
    }
    if (Tcl_GetIndexFromObjStruct(interp, objv[1], aSubCommand, sizeof(struct InterpSubCommand), "option", 0, &choice)){
        return TCL_ERROR;
    }
    nMin = aSubCommand[choice].nMinArgs;
    nMax = aSubCommand[choice].nMaxArgs;
    if (nMin >= 0 && objc < nMin+2 || nMax >= 0 && objc > nMax+2) {
        Tcl_WrongNumArgs(interp, 2, objv, aSubCommand[choice].zArgs);
        return TCL_ERROR;
    }
    switch (aSubCommand[choice].eSymbol) {
        case INTERP_EVAL: { // qjs eval ?OPTIONS? PROGRAM-TEXT
            rc = interpEval(qjs, objc, objv); // Evaluate a JavaScript script.
            break;
        }
		case INTERP_FUNC: {
            rc = interpFunction(qjs, objc, objv);
            break;
        }
		case INTERP_PROC: {
            rc = interpProc(qjs, objc, objv);
            break;
        }
		case INTERP_CALL: {
            rc = interpCall(qjs, objc, objv);
            break;
        }
        case INTERP_NODE: { // qjs node JAVASCRIPT-OBJECT
            createNode(qjs, objv[2]);
            break;
        }
        case INTERP_GLOBAL: { // qjs global PROPERTY JAVASCRIPT-VALUE
			rc = interpGlobalSet(qjs, objc>2?objv[2]:NULL, objc>3?objv[3]:NULL);
            break;
        }
        case INTERP_TOSTRING: {  /* $interp tostring VALUE */
            JSValue val = objToValue(qjs->ctx, objv[2]);
            Tcl_SetObjResult(interp, stringToObj(qjs->ctx, val));
			JS_FreeValue(qjs->ctx, val);
            break;
        }
        case INTERP_DISPATCH: { // $interp dispatch TARGET-COMMAND EVENT-COMMAND
            rc = eventDispatchCmd(clientData, interp, objc, objv);
			break;
        }
        case INTERP_DEBUG: { // interp debug SUB-COMMAND
            rc = interpDebug(qjs, objc, objv);
            break;
        }
        case INTERP_EVENTS: {
            rc = eventDumpCmd(clientData, interp, objc, objv);
			break;
        }
		case INTERP_LOG: {
            if (qjs->pLog) {
                Tcl_DecrRefCount(qjs->pLog);
                qjs->pLog = NULL;
            }
            if (Tcl_GetCharLength(objv[2])) {
                qjs->pLog = objv[2];
                Tcl_IncrRefCount(qjs->pLog);
            }
            break;
        }
        case INTERP_DESTROY: { // qjs destroy
            /* Deleting the command automatically calls delInterpCmd() */
            Tcl_DeleteCommand(interp, Tcl_GetString(objv[0]));
            break;
        }
	}
    return rc;
}

static JSRuntime *runtime = NULL;
/*
 *---------------------------------------------------------------------------
 *
 * tclQjsInterp --
 *
 *     Implementation of [::qjs::interp].
 *
 *     Creates a new JavaScript interpreter object-command.
 *
 * Results:
 *     TCL_OK or TCL_ERROR.
 *
 * Side effects:
 *     See above.
 *
 *---------------------------------------------------------------------------
 */
static int tclQjsInterp(ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    char zCmd[64];
    QjsInterp *qjs;
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "GLOBAL-OBJCOMMAND");
        return TCL_ERROR;
    }
	if (!numQjsInterp - numFreeInterp) {
		runtime = JS_NewRuntime();
		getExoticObj(runtime);
	}
    qjs = js_mallocz_rt(runtime, sizeof(QjsInterp));
    qjs->rt = runtime;
    qjs->ctx = JS_NewContext(runtime);
    qjs->interp = interp;
	
	Tcl_InitHashTable(&qjs->objects, TCL_STRING_KEYS);
	JS_SetRuntimeOpaque(runtime, interp);
	JS_SetContextOpaque(qjs->ctx, (ContextOpaque*)qjs);
	
	JSValue Global = JS_GetGlobalObject(qjs->ctx);
	eventTargetGlobalInit(qjs, Global);  // This must be done BEFORE any Tcl-JS objects are created
	qjs->global = findOrCreateObject(qjs, objv[1]);
	assert(1 == JS_SetPrototype(qjs->ctx, Global, qjs->global));
    /* Initialize the object's event subsystem */
	interpTimeoutInit(qjs->ctx, Global);
	JS_FreeValue(qjs->ctx, Global);

    snprintf(zCmd, sizeof(zCmd), "::qjs::interp_%d", numQjsInterp++);
    Tcl_CreateObjCommand(interp, zCmd, interpCmd, qjs, delInterpCmd);
    Tcl_SetResult(interp, zCmd, TCL_VOLATILE);
    return TCL_OK;
}

static inline Tcl_Obj *atomToObj(JSContext *ctx, JSAtom atm) {
	size_t l;
	const char *s = JS_AtomToCStringLen(ctx, &l, atm);
	Tcl_Obj *p = Tcl_NewStringObj(s, l);
	JS_FreeCString(ctx, s);
	return p;
}

static JSValue 
QjsTcl_Get(JSContext *ctx, JSValue obj, JSAtom prop, JSValueConst rec)
{
	for(JSValue o = JS_DupValue(ctx, rec); !JS_IsNull(o); o = JS_GetPrototype(ctx, o)){
		JSPropertyDescriptor desc;  // First, check if the property exists normally
		if (JS_GetOwnProperty(ctx, &desc, o, prop) > 0) {
			JS_FreeValue(ctx, o);
			return desc.value;
		}
		JS_FreeValue(ctx, o);
	}
	ContextOpaque *p = JS_GetContextOpaque(ctx);
	if (!p) return JS_ThrowTypeError(ctx, "Tcl interpreter not available");
	
	callQjsTclMethod(p->interp, p->pLog, obj, atomToObj(ctx, prop), NULL);
	JSValue res = objToValue(ctx, Tcl_GetObjResult(p->interp));
	// Caching of DOM methods
	if (JS_IsFunction(ctx, res)) JS_DefinePropertyValue(ctx, rec, prop, JS_DupValue(ctx, res), 0);
	return res;
}

static int 
QjsTcl_Set(JSContext *ctx, JSValueConst obj, JSAtom prop, JSValueConst val, JSValueConst rec, int f)
{
	int nObj = 0, rc;  // First, check if the property exists normally
	for(JSValue o = JS_DupValue(ctx, rec); !JS_IsNull(o); o = JS_GetPrototype(ctx, o)){
		if (JS_GetOwnProperty(ctx, NULL, o, prop) > 0 || JS_IsFunction(ctx, val)) {
			JS_FreeValue(ctx, o);
			return JS_DefinePropertyValue(ctx, o, prop, JS_DupValue(ctx, val), f);
		}
		JS_FreeValue(ctx, o);
	}
	ContextOpaque *p = JS_GetContextOpaque(ctx);
	if (!p) {
		JS_ThrowTypeError(ctx, "Tcl interpreter not available");
		return -1;
	}
    Tcl_Obj *pVal = argValueToTcl((QjsInterp*)p, val, &nObj);
	Tcl_IncrRefCount(pVal);
	rc = callQjsTclMethod(p->interp, p->pLog, obj, atomToObj(ctx, prop), pVal);
	Tcl_DecrRefCount(pVal);
    removeTransientRefs((QjsInterp*)p, nObj);
	if (rc != TCL_OK) {
		throwTclError(ctx, p->interp);
		return -1;
	} if (!strcmp(Tcl_GetStringResult(p->interp), "NATIVE")) {
		return JS_DefinePropertyValue(ctx, obj, prop, JS_DupValue(ctx, val), f);
	}
    return 1;
}

static int QjsTcl_Has(JSContext *ctx, JSValueConst obj, JSAtom prop)
{
	JSValue val = QjsTcl_Get(ctx, obj, prop, obj);
	int8_t has = !JS_IsUndefined(val);
	JS_FreeValue(ctx, val);
    return has;
}

static int 
QjsTcl_Enumerator(JSContext *ctx, JSPropertyEnum **pTab, uint32_t *pLen, JSValueConst obj)
{
    ContextOpaque *ctxOp = JS_GetContextOpaque(ctx);
    Tcl_Interp *interp = ctxOp->interp;

    Tcl_Obj **apRet;         /* List elements of pRet */
    int rc, nRet;            /* size of apString */
    JSPropertyEnum *pEnum;

    rc = callQjsTclMethod(interp, ctxOp->pLog, obj, Tcl_NewStringObj("Enumerator", 10), NULL);
    if (rc != TCL_OK) goto error;

    rc = Tcl_ListObjGetElements(interp, Tcl_GetObjResult(interp), &nRet, &apRet);
    if (rc != TCL_OK) goto error;

    pEnum = js_malloc(ctx, sizeof(pEnum[0]) * nRet);

    for (int i = 0; i < nRet; i++) {
        pEnum[i].atom = JS_NewAtom(ctx, Tcl_GetString(apRet[i]));
    }
	*pTab = pEnum;
	*pLen = nRet;

    return 0;
	error:
		js_free(ctx, pEnum);
		throwTclError(ctx, interp);
		return -1;
}

// Create the exotic methods structure
static JSClassExoticMethods tclExoticMethods = {
    .get_property = QjsTcl_Get,
    .set_property = QjsTcl_Set,
	.has_property = QjsTcl_Has,
	.get_own_property_names = QjsTcl_Enumerator,
};
static JSClassDef QjsTclClass = {
    "Tcl Object",
    .finalizer = finalizeObject,
    .gc_mark = listenerMark,
	.exotic = &tclExoticMethods,  // Link to exotic methods
};

static JSValue 
tclCallOrConstruct(JSContext *ctx, JSValueConst obj, JSValueConst this, int argc, JSValueConst *argv, int f)
{
	int rc, i, nObj = 0, nWI;
    QjsTclObject *p = JS_GetOpaque(obj, QjsTclCallClassId);
	QjsInterp *qjs = JS_GetContextOpaque(ctx);

    /* Make sure there is enough space to marshall the arguments */
	allocWordArray(qjs, p, argc+1);
	
	/* Set and reference-count "this" argument */
	if (JS_IsUndefined(this)) this = qjs->global;
	JSClassID id = f & JS_CALL_FLAG_CONSTRUCTOR ? QjsTclCallClassId : QjsTclClassId;
	QjsTclObject *pTh = JS_GetOpaque(this, id);
	p->apWord[p->nWord] = pTh->pObj;
	Tcl_IncrRefCount(p->apWord[p->nWord]);
	
	/* Convert arguments and increment reference counts in one loop */
    for (i = 0; i < argc; i++) {
		nWI = p->nWord + i + 1;
        p->apWord[nWI] = argValueToTcl(qjs, argv[i], &nObj);
        Tcl_IncrRefCount(p->apWord[nWI]);
    }
	rc = evalObjv(qjs->interp, p->nWord+argc+1, p->apWord);
	for (i = 0; i < argc; i++) {
        Tcl_DecrRefCount(p->apWord[p->nWord + i]);
    }
    removeTransientRefs(qjs, nObj);
	if (rc != TCL_OK) return throwTclError(ctx, qjs->interp);
	return objToValue(ctx, Tcl_GetObjResult(qjs->interp));
}

static JSClassDef QjsTclCallClass = {
    "Tcl Method",
    .finalizer = finalizeObject,
    .gc_mark = listenerMark,
	.exotic = &tclExoticMethods,  // Link to exotic methods
	.call = tclCallOrConstruct,
};
static void getExoticObj(JSRuntime *rt) {
    JS_NewClass(rt, QjsTclClassId, &QjsTclClass);
    JS_NewClass(rt, QjsTclCallClassId, &QjsTclCallClass);
}

static int 
tclQjsAlloc(ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
    Tcl_SetObjResult(interp, debugAlloc(runtime));
    return TCL_OK;
}

static int 
tclQjsCollect(ClientData cd, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
{
	if (numQjsInterp - numFreeInterp > 0) JS_RunGC(runtime);
    return TCL_OK;
}

/* Package initializer */
int Tclqjs_Init(Tcl_Interp *interp) {
    /* Require stubs libraries version 8.4 or greater. */
#ifdef USE_TCL_STUBS
    if (Tcl_InitStubs(interp, "8.4", 0) == 0) {
        return TCL_ERROR;
    }
#endif
    JS_NewClassID(&QjsTclClassId);
    JS_NewClassID(&QjsTclCallClassId);
	
    Tcl_PkgProvide(interp, "Tclqjs", "0.1");
    Tcl_CreateObjCommand(interp, "::qjs::interp", tclQjsInterp,  NULL, NULL);
    Tcl_CreateObjCommand(interp, "::qjs::alloc",  tclQjsAlloc,   NULL, NULL);
	Tcl_CreateObjCommand(interp, "::qjs::format", tclQjsFormat,  NULL, NULL);
    Tcl_CreateObjCommand(interp, "::qjs::gc",     tclQjsCollect, NULL, NULL);
    // TODO: Add more commands (e.g., ::qjs::class, etc.)
    return TCL_OK;
}
#include "hv3events.c"
