
/* 
 * DO NOT EDIT!
 *
 * The code in this file was automatically generated. See the files
 * src/tokenlist.tcl and tools/maketokens.tcl from the tkhtml source
 * distribution.
 */


#define Html_Text    1
#define Html_Space   2
#define Html_Unknown 3
#define Html_Block   4
#define HtmlIsMarkup(X) ((X)->base.type>Html_Block)
#define Html_A               5
#define Html_ABBR            6
#define Html_ACRONYM         7
#define Html_ADDRESS         8
#define Html_APPLET          9
#define Html_AREA            10
#define Html_BASE            11
#define Html_BASEFONT        12
#define Html_B               13
#define Html_BDO             14
#define Html_BIG             15
#define Html_BLOCKQUOTE      16
#define Html_BODY            17
#define Html_BR              18
#define Html_BUTTON          19
#define Html_CAPTION         20
#define Html_CENTER          21
#define Html_CITE            22
#define Html_CODE            23
#define Html_COL             24
#define Html_DD              25
#define Html_DEL             26
#define Html_DFN             27
#define Html_DIR             28
#define Html_DIV             29
#define Html_DL              30
#define Html_DT              31
#define Html_EM              32
#define Html_FIELDSET        33
#define Html_FONT            34
#define Html_FORM            35
#define Html_FRAME           36
#define Html_FRAMESET        37
#define Html_H1              38
#define Html_H2              39
#define Html_H3              40
#define Html_H4              41
#define Html_H5              42
#define Html_H6              43
#define Html_HEAD            44
#define Html_HR              45
#define Html_HTML            46
#define Html_I               47
#define Html_IFRAME          48
#define Html_IMG             49
#define Html_INPUT           50
#define Html_ISINDEX         51
#define Html_KBD             52
#define Html_LABEL           53
#define Html_LEGEND          54
#define Html_LI              55
#define Html_LINK            56
#define Html_MAP             57
#define Html_MENU            58
#define Html_META            59
#define Html_NOFRAMES        60
#define Html_NOSCRIPT        61
#define Html_OBJECT          62
#define Html_OL              63
#define Html_OPTGROUP        64
#define Html_OPTION          65
#define Html_P               66
#define Html_PARAM           67
#define Html_PRE             68
#define Html_Q               69
#define Html_S               70
#define Html_SAMP            71
#define Html_SCRIPT          72
#define Html_SELECT          73
#define Html_SMALL           74
#define Html_SPAN            75
#define Html_STRIKE          76
#define Html_STRONG          77
#define Html_STYLE           78
#define Html_SUB             79
#define Html_SUP             80
#define Html_TABLE           81
#define Html_TBODY           82
#define Html_TD              83
#define Html_TEXTAREA        84
#define Html_TFOOT           85
#define Html_TH              86
#define Html_THEAD           87
#define Html_TITLE           88
#define Html_TR              89
#define Html_TT              90
#define Html_U               91
#define Html_UL              92
#define Html_VAR             93
#define Html_ARTICLE         94
#define Html_ASIDE           95
#define Html_AUDIO           96
#define Html_CANVAS          97
#define Html_DATALIST        98
#define Html_DETAILS         99
#define Html_FIGCAPTION      100
#define Html_FIGURE          101
#define Html_FOOTER          102
#define Html_HEADER          103
#define Html_HGROUP          104
#define Html_KEYGEN          105
#define Html_MAIN            106
#define Html_MARK            107
#define Html_METER           108
#define Html_NAV             109
#define Html_OUTPUT          110
#define Html_PROGRESS        111
#define Html_RP              112
#define Html_RT              113
#define Html_RUBY            114
#define Html_SECTION         115
#define Html_SOURCE          116
#define Html_SUMMARY         117
#define Html_TIME            118
#define Html_TRACK           119
#define Html_VIDEO           120
#define Html_COMMENT         121
#define Html_EMBED           122
#define Html_LISTING         123
#define Html_MARQUEE         124
#define Html_NEXTID          125
#define Html_NOBR            126
#define Html_NOEMBED         127
#define Html_PLAINTEXT       128
#define Html_WBR             129
#define Html_XMP             130
#define Html_BGSOUND         131
#define Html_TypeCount 132
#define HTML_MARKUP_HASH_SIZE 143
#define HTML_MARKUP_COUNT 127
