name: C/C++ CI Linux x64

on:
  push:
    branches: [ "3.1-TclTk9" ]
  pull_request:
    branches: [ "3.1-TclTk9" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: rn1
      run: sudo apt install python3-tk
    - name: rn2
      run: pip install tkinterweb
    - name: compile
      run: python ./compile.py -n -t -v
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: .
