name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - with:
        arch: armv7
        distro: ubuntu18.04
    - uses: actions/checkout@v3
    - run: TCL=/usr
    - run: export PATH=$TCL/bin:$PATH
    - run: tclsh src/cssprop.tcl && tclsh src/tokenlist.txt && tclsh src/mkdefaultstyle.tcl > htmldefaultstyle.c
    - run: mv *.c src && mv *.h src
    - run: mkdir build && cd build
    - run: ../configure CC="gcc -static-libgcc" --with-tcl=$TCL/lib/tcl8.6 --with-tk=$TCL/lib/tk8.6 --with-tclinclude=$TCL/include/tcl8.6 --with-tkinclude=$TCL/include/tcl8.6
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
