name: C/C++ CI Linux ARM With Cairo Graphics

on:
  push:
    branches: [ "3.1-TclTk9" ]
  pull_request:
    branches: [ "3.1-TclTk9" ]

jobs:
  build:

    runs-on: ubuntu-26.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: sudo apt-get install -y tcl9.0-dev tk9.0-dev python3-tk
    - name: Compile
      run: python ./compile.py -n -t -w tclsh9.0
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: .
