name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - run: export PATH=$TCL/bin:$PATH
    - run: tclsh src/cssprop.tcl && tclsh src/tokenlist.txt && tclsh src/mkdefaultstyle.tcl > htmldefaultstyle.c 
    - run: chmod +rwx ./configure
    - run: mv *.c src && mv *.h src
    - run: ls -l /usr/local/Cellar/tcl-tk/8.6.13/lib/
    - run: ls -l /usr/local/Cellar/tcl-tk/8.6.13/bin/
    - run: ls -l /usr/local/Cellar/tcl-tk/8.6.13/include/
    - run: ls -l /System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/
    - run: ls -l /usr/local/Cellar/tcl-tk/
    - run: ls -l /System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/
    - run: ls -l /System/Volumes/Data/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/
    - run: ls -l /usr/bin
    - run: ls -l /usr
    - run: ls -l /usr/sbin
    - run: ls -l /usr/share
    - run: ls -l /usr/standalone
    - run: ls -l /usr/local
    - run: ls -l /usr/libexec
    - run: ls -l /usr/lib
    - name: configure
      run: ./configure CC="gcc -static-libgcc" --with-tcl=/usr/lib --with-tk=/usr/lib --with-tclinclude=/usr/include --with-tkinclude=/usr/include
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck