name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install tcl-dev tk-dev
    - uses: actions/checkout@v3
    - run: TCL=/usr/
    - run: ls -l /usr
    - run: export PATH=$TCL/bin:$PATH
    - run: tclsh src/cssprop.tcl && tclsh src/tokenlist.txt && tclsh src/mkdefaultstyle.tcl > htmldefaultstyle.c 
    - run: chmod +rwx ./configure
    - run: mv *.c src && mv *.h src
    - name: configure
      run: ./configure CC="gcc -static-libgcc" --with-tcl=$TCL/lib --with-tk=$TCL/lib --with-tclinclude=$TCL/include --with-tkinclude=$TCL/include
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
