name: C/C++ CI Macos Silicon With Cairo Graphics

on:
  push:
    branches: [ "3.1-TclTk9" ]
  pull_request:
    branches: [ "3.1-TclTk9" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: brew install tcl-tk cairo
    - name: Compile
      env:
        PYTHONUNBUFFERED: "1" 
      run: python ./compile.py -n -t -v
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: .
