name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Install Tcl/Tk
      run: brew install tcl-tk
    - name: Prepare files
      run: pip3 install tkinterweb
    - name: Configure
      run: python3 -m tkinterweb.__init__ Demo
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: .
